apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: pelp346hz-go
  janus-idp.io/tekton: pelp346hz-go
  backstage.io/kubernetes-id: pelp346hz-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: pelp346hz-go
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
